version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "cargo"
    directory: "/chess/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "cargo"
    directory: "/eval/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "cargo"
    directory: "/nnue/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "cargo"
    directory: "/search/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "cargo"
    directory: "/util/"
    schedule:
      interval: "weekly"
      day: "saturday"