[package]
name = "chessboard"
version = "0.1.0"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
edition = "2018"
description = "A CLI for chess"
repository = "https://github.com/brunocodutra/chessboard.git"
license = "GPL-3.0"
readme = "README.md"
keywords = ["chess", "cli"]

[dependencies]
anyhow = "1.0.43"
async-trait = "0.1.51"
clap = "2.33.3"
derive_more = "0.99.16"
futures = "0.3.17"
rustyline = "9.0.0"
shakmaty = "0.19.0"
smol = "1.2.5"
structopt = "0.3.23"
tracing = "0.1.26"
tracing-subscriber = "0.2.23"
url = "2.2.2"
vampirc-uci = "0.11.0"

[dev-dependencies]
mockall = "0.9.1"
port_check = "0.1.5"
proptest = "1.0.0"
proptest-derive = "0.3.0"
