[package]
name = "chessboard"
version = "0.1.0"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
edition = "2021"
description = "A sandbox for experimenting with chess engines"
repository = "https://github.com/brunocodutra/chessboard.git"
license = "GPL-3.0"
readme = "README.md"
keywords = ["chess"]

[dependencies]
anyhow = { version = "1.0.69", default-features = false, features = ["std"] }
arrayvec = { version = "0.7.2", default-features = false, features = ["std"] }
async-stream = { version = "0.3.5", default-features = false }
atomic = { version = "0.5.3", default-features = false, features = ["std"] }
bitflags = { version = "2.3.1", default-features = false }
clap = { version = "4.3.3", default-features = false, features = [
    "color",
    "derive",
    "error-context",
    "help",
    "std",
    "suggestions",
    "usage",
] }
derive_more = { version = "0.99.16", default-features = false, features = [
    "add",
    "constructor",
    "deref",
    "display",
    "error",
    "from",
    "into_iterator",
    "not",
] }
futures-util = { version = "0.3.26", default-features = false, features = ["alloc"] }
humantime-serde = { version = "1.1.1", default-features = false }
num-traits = { version = "0.2.15", default-features = false, features = ["std"] }
proptest = { version = "1.2.0", default-features = false, features = ["std"] }
rayon = { version = "1.7.0", default-features = false }
ron = { version = "0.8.0", default-features = false }
serde = { version = "1.0.164", default-features = false, features = ["derive", "std"] }
shakmaty = { version = "0.25.0", default-features = false, features = ["std"] }
test-strategy = { version = "0.3.0", default-features = false }
tokio = { version = "1.28.2", default-features = false, features = [
    "io-std",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
    "sync",
    "time",
] }
tracing = { version = "0.1.37", default-features = false, features = ["attributes", "std"] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
    "ansi",
    "fmt",
    "registry",
    "std",
] }
vampirc-uci = { version = "0.11.0", default-features = false }

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false, features = ["rayon"] }
mockall = { version = "0.11.4", default-features = false }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.dev]
opt-level = 1

[profile.bench]
debug = true

[lib]
name = "lib"
path = "lib/lib.rs"
bench = false

[[bin]]
name = "cli"
path = "bin/main.rs"
bench = false

[[bench]]
name = "ttd"
harness = false

[[bench]]
name = "ttm"
harness = false
