[package]
name = "chessboard"
version = "0.1.0"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
edition = "2018"
description = "A CLI for chess"
repository = "https://github.com/brunocodutra/chessboard.git"
license = "GPL-3.0"
readme = "README.md"
keywords = ["chess", "cli"]

[dependencies]
anyhow = "1.0.43"
async-trait = "0.1.51"
clap = { version = "3.1.9", default-features = false, features = ["derive", "std"] }
derive_more = "0.99.16"
futures = "0.3.17"
rustyline = "9.0.0"
shakmaty = "0.21.1"
smol = "1.2.5"
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
url = "2.2.2"
vampirc-uci = "0.11.0"

[dev-dependencies]
mockall = "0.11.0"
proptest = "1.0.0"
test-strategy = "0.2.0"
