[package]
name = "chessboard"
version = "0.1.0"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
edition = "2018"
description = "A CLI for chess"
repository = "https://github.com/brunocodutra/chessboard.git"
license = "GPL-3.0"
readme = "README.md"
keywords = ["chess", "cli"]

[dependencies]
anyhow = "1.0.32"
async-std = "1.6.3"
async-trait = "0.1.38"
chess = "3.1.1"
clap = "2.33.3"
derivative = "2.1.1"
derive_more = "0.99.9"
futures = "0.3.5"
indicatif = "0.15.0"
rustyline = "6.2.0"
smol = "0.3.3"
structopt = "0.3.17"
tracing = { version = "0.1.19", features = ["log"] }
tracing-appender = "0.1.1"
tracing-futures = { version = "0.2.4", features = ["std", "std-future"], default-features = false }
tracing-subscriber = "0.2.11"
url = "2.1.1"
vampirc-uci = { version = "0.10.1", features = ["chess"] }

[dev-dependencies]
mockall = "0.7.2"
port_check = "0.1.5"
proptest = "0.10.1"
proptest-derive = "0.2.0"
