[package]
name = "chessboard"
version = "0.1.0"
authors = ["Bruno Dutra <brunocodutra@gmail.com>"]
edition = "2021"
description = "A sandbox for experimenting with chess engines"
repository = "https://github.com/brunocodutra/chessboard.git"
license = "GPL-3.0"
readme = "README.md"
keywords = ["chess"]

[dependencies]
anyhow = { version = "1.0.62", default-features = false, features = ["std"] }
async-trait = { version = "0.1.57", default-features = false }
atomic = { version = "0.5.1", default-features = false, features = ["std"] }
bitvec = { version = "1.0.1", default-features = false, features = ["atomic", "std"] }
clap = { version = "3.1.18", default-features = false, features = ["derive", "std"] }
derive_more = { version = "0.99.16", default-features = false, features = ["add", "add_assign", "constructor", "deref", "display", "error", "from"] }
humantime-serde = { version = "1.1.1", default-features = false }
libm = { version = "0.2.5", default-features = false }
rayon = { version = "1.5.3", default-features = false }
ron = { version = "0.8.0", default-features = false }
serde = { version = "1.0.143", default-features = false, features = ["derive", "std"] }
shakmaty = { version = "0.21.2", default-features = false }
tokio = { version = "1.20.1", default-features = false, features = ["io-std", "io-util", "macros", "process", "rt-multi-thread", "time"] }
tracing = { version = "0.1.36", default-features = false, features = ["attributes", "std"] }
tracing-subscriber = { version = "0.3.15", default-features = false, features = ["ansi", "fmt", "registry", "std"] }
vampirc-uci = { version = "0.11.0", default-features = false }

[dev-dependencies]
criterion = { version = "0.3.6", default-features = false }
mockall = { version = "0.11.2", default-features = false }
pgn-reader = { version = "0.20.0", default-features = false }
proptest = { version = "1.0.0", default-features = false, features = ["std"] }
test-strategy = { version = "0.2.0", default-features = false }

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1

[profile.cov]
inherits = "dev"
opt-level = 0
overflow-checks = false

[profile.bench]
debug = true

[[bench]]
name = "minimax"
harness = false
