[tasks.dist]
command = "cargo"
args = [
    "build",
    "-Zbuild-std=core,alloc,std,panic_abort",
    "-Zbuild-std-features=panic_immediate_abort",
    "--target=${CARGO_MAKE_CRATE_TARGET_TRIPLE}",
    "--release",
]
