[tasks.env]
env = { TARGET = "${CARGO_MAKE_CRATE_TARGET_TRIPLE}" }

[tasks.env.linux]
env = { TARGET = "x86_64-unknown-linux-musl" }

[tasks.env.mac]
env = { TARGET = "x86_64-apple-darwin" }

[tasks.env.windows]
env = { TARGET = "x86_64-pc-windows-gnu" }

[tasks.dist]
dependencies = ["env"]
command = "cargo"
args = [
    "build",
    "-Zbuild-std=core,alloc,std,panic_abort",
    "-Zbuild-std-features=panic_immediate_abort",
    "-Zunstable-options",
    "--config=build.rustflags = [\"-Ctarget-feature=+crt-static\", \"-Crelocation-model=static\"]",
    "--target=${TARGET}",
    "--release",
]
