[tasks.env]
env = { TARGET = "${CARGO_MAKE_CRATE_TARGET_TRIPLE}", FLAGS = '[]' }

[tasks.env.linux]
env = { TARGET = "x86_64-unknown-linux-musl", FLAGS = '["-Ctarget-feature=+crt-static", "-Crelocation-model=static"]' }

[tasks.env.mac]
env = { TARGET = "x86_64-apple-darwin", FLAGS = '["-Ctarget-feature=+crt-static", "-Crelocation-model=static"]' }

[tasks.env.windows]
env = { TARGET = "x86_64-pc-windows-msvc", FLAGS = '["-Ctarget-feature=+crt-static"]' }

[tasks.dist]
dependencies = ["env"]
command = "cargo"
args = [
    "build",
    "-Zbuild-std=core,alloc,std,panic_abort",
    "-Zbuild-std-features=panic_immediate_abort",
    "-Zunstable-options",
    "--config=build.rustflags = ${FLAGS}",
    "--target=${TARGET}",
    "--release",
]
