[advisories]
ignore = [
    "RUSTSEC-2020-0159", # Potential segfault in `localtime_r` invocations
    "RUSTSEC-2020-0071", # Potential segfault in the time crate
    "RUSTSEC-2021-0047", # SliceDeque::drain_filter can double drop an element if the predicate panics
]